export const SEARCH_USERS = "SEARCH_USERS";
export const GET_USER = "GET_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const GET_REPOS = "GET_REPOS";
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_EPISODES = "GET_EPISODES";
export const GET_EPISODE = "GET_EPISODE";

export const SET_PROFILE = "GET_PROFILE";
export const SET_IS_LOADING_PROFILE = "SET_IS_LOADING_PROFILE";

export const POST_FOR_PINNING = "POST_FOR_PINNING";
export const UPDATE_STATE = "UPDATE_STATE";
export const UPDATE_SELECTED_ANIMAL = "UPDATE_SELECTED_ANIMAL";
